### ISSUE TITLE
TableCell component

### ISSUE THREAD

**Issue by muziejus** [muziejus/wandertext#196]
It:

- [x] Displays the associated property 05143f6 
- [x] Displays the property as a Place if it is 2c7c72b
- [x] Displays the property as a Date if it is 1d48e53
- [x] Displays the input as disabled if the prop is owned by another or is readonly 98cfe93
- [x] Validates against changes
- [x] Indicates a dirty attribute
- [x] Saves when the active row changes. #198
